# Modele sklearn

## Importowanie bibliotek

In [1]:
import pandas as pd

from mlxtend.data import loadlocal_mnist

from sklearn import model_selection
from sklearn import metrics

from sklearn import linear_model
from sklearn import tree
from sklearn import ensemble
from sklearn import neural_network

## Inicjalizacja konfiguracji

In [2]:
class config:
    
    # Ścieżki do plików
    DOWNLOADED_IMAGES_PATH = "data/t10k-images.idx3-ubyte"
    DOWNLOADED_LABELS_PATH = "data/t10k-labels.idx1-ubyte"

    # Ogólne ustawienia projektu
    RANDOMIZE_DATA = True
    FOLDS_CNT = 5

## Wczytanie danych

In [3]:
# Wczytanie danych z plików
X, y = loadlocal_mnist(
    images_path=config.DOWNLOADED_IMAGES_PATH,
    labels_path=config.DOWNLOADED_LABELS_PATH
)

# Generowanie kolumn z id pikseli
pixel_columns = [f"pixel{i}" for i in range(len(X[0]))]

# Stworzenie pandas DataFrame
df = pd.DataFrame(X, columns=pixel_columns)

# Dodanie etykiety
df["label"] = y

# Wyświetlenie danych
df

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,label
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,7
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
9996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
9998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
9999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,6

## Podział danych na foldy

<img src="./images/image1.png" alt="image1" width="1300"/>
<!-- ![image1](./images/image1.png) -->
<!-- ![image1](https://towardsdatascience.com/wp-content/uploads/2023/12/1N45hocCMP0u4nXLe0WuSvw.png) -->

In [4]:
# Stworzenie kolumny kfold
df["kfold"] = -1

# Podział danych na segmenty oraz ewentualnie przelosowanie danych
folds_model = model_selection.StratifiedKFold(
    n_splits=config.FOLDS_CNT,
    shuffle=config.RANDOMIZE_DATA
)
for fold, (train, test) in enumerate(folds_model.split(df, df["label"].values)):
    df.loc[test, "kfold"] = fold
    
    print(f"{fold}. {train}, {test}")

# Wyświetlenie danych
df

0. [   0    1    3 ... 9997 9998 9999], [   2    5    9 ... 9972 9977 9990]
1. [   1    2    3 ... 9994 9995 9997], [   0    6   10 ... 9996 9998 9999]
2. [   0    1    2 ... 9997 9998 9999], [  17   28   31 ... 9992 9993 9995]
3. [   0    2    3 ... 9997 9998 9999], [   1    4    7 ... 9979 9983 9989]
4. [   0    1    2 ... 9996 9998 9999], [   3    8   13 ... 9991 9994 9997]

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,label,kfold
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,7,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,3
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2,2
9996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3,1
9997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,4,4
9998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,5,1
9999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,6,1

## Dyspozytor modelu

In [16]:
class model_dispatcher:
    
    # Tablica z nazwami modeli
    model_names = [
        # "logistic_regression",
        "SGDClassifier",
        "decision_tree_gini",
        "decision_tree_entropy",
        "decision_tree_log_loss",
        "random_forest",
        "neural_network_default",
        "neural_network_with_settings"
    ]

    # Słownik z nazwami modeli oraz klasami
    models = {
        "logistic_regression": linear_model.LogisticRegression(
            max_iter=6000
        ),
        "SGDClassifier": linear_model.SGDClassifier(),
        "decision_tree_gini": tree.DecisionTreeClassifier(
            criterion="gini"
        ),
        "decision_tree_entropy": tree.DecisionTreeClassifier(
            criterion="entropy"
        ),
        "decision_tree_log_loss": tree.DecisionTreeClassifier(
            criterion="log_loss"
        ),
        "random_forest": ensemble.RandomForestClassifier(),
        "neural_network_default": neural_network.MLPClassifier(),
        "neural_network_with_settings": neural_network.MLPClassifier(
            hidden_layer_sizes=(256, 256),
            activation="relu",
            solver="adam",
            batch_size=64,
            max_iter=10,
            verbose=True
        )
    }

## Trenowanie oraz testowanie modelu

In [12]:
def use_model(df_train, df_test, model, metrics_func):
    
    # Podział danych na odpowiednie zmienne
    x_train = df_train.loc[:, df_train.columns != "label"].values
    y_train = df_train.loc[:, "label"].values

    x_test = df_test.loc[:, df_test.columns != "label"].values
    y_test = df_test.loc[:, "label"].values
    
    # Trenowanie modelu
    model.fit(x_train, y_train)

    # Wykorzystanie modelu
    predicted_data = model.predict(x_test)
    
    # Obliczenie oraz zwrócenie wyników metryki
    scores = metrics_func(
        y_true=y_test,
        y_pred=predicted_data
    )
    return scores

In [17]:
# Inicjalizacja słownika z modelami oraz metrykami ich wyników
metrics_dict = {}

# Pętla przechodząca przez modele
for model_name in model_dispatcher.model_names:
    model = model_dispatcher.models[model_name]
    
    # Inicjalizacja nowego elementu w słowniku
    metrics_dict[model_name] = []

    # Testowanie modelu na różnych foldach
    for fold in range(config.FOLDS_CNT):
        
        # Inicjalizacja train oraz test dataframe
        df_train = df.loc[df["kfold"] != fold, df.columns != "kfold"]
        df_test = df.loc[df["kfold"] == fold, df.columns != "kfold"]

        # Obliczanie accuracy
        score = use_model(df_train, df_test, model, metrics.accuracy_score)

        # Dodanie accuracy do tablicy wyników aktualnego modelu
        metrics_dict[model_name].append(score)

        # Wypisanie accuracy
        print(f"{model_name}: {fold} - {score:.3f}")

SGDClassifier: 0 - 0.889
SGDClassifier: 1 - 0.854
SGDClassifier: 2 - 0.869
SGDClassifier: 3 - 0.867
SGDClassifier: 4 - 0.867
decision_tree_gini: 0 - 0.814
decision_tree_gini: 1 - 0.803
decision_tree_gini: 2 - 0.803
decision_tree_gini: 3 - 0.799
decision_tree_gini: 4 - 0.804
decision_tree_entropy: 0 - 0.812
decision_tree_entropy: 1 - 0.831
decision_tree_entropy: 2 - 0.801
decision_tree_entropy: 3 - 0.802
decision_tree_entropy: 4 - 0.816
decision_tree_log_loss: 0 - 0.814
decision_tree_log_loss: 1 - 0.824
decision_tree_log_loss: 2 - 0.804
decision_tree_log_loss: 3 - 0.810
decision_tree_log_loss: 4 - 0.821
random_forest: 0 - 0.950
random_forest: 1 - 0.955
random_forest: 2 - 0.954
random_forest: 3 - 0.949
random_forest: 4 - 0.957
neural_network_default: 0 - 0.929
neural_network_default: 1 - 0.933
neural_network_default: 2 - 0.923
neural_network_default: 3 - 0.919
neural_network_default: 4 - 0.924
Iteration 1, loss = 4.18848512
Iteration 2, loss = 0.88559776
Iteration 3, loss = 0.43370442
Iteration 4, loss = 0.38802993
Iteration 5, loss = 0.27296404
Iteration 6, loss = 0.21429289
Iteration 7, loss = 0.23575652
Iteration 8, loss = 0.16298139
Iteration 9, loss = 0.23972805
Iteration 10, loss = 0.28611591
neural_network_with_settings: 0 - 0.933

/home/wikolego/miniconda3/envs/ml-3/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(

Iteration 1, loss = 4.28888804
Iteration 2, loss = 1.05966445
Iteration 3, loss = 0.57538442
Iteration 4, loss = 0.35098997
Iteration 5, loss = 0.33202159
Iteration 6, loss = 0.26438738
Iteration 7, loss = 0.20198620
Iteration 8, loss = 0.26719587
Iteration 9, loss = 0.34869065
Iteration 10, loss = 0.19071341
neural_network_with_settings: 1 - 0.939

/home/wikolego/miniconda3/envs/ml-3/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(

Iteration 1, loss = 4.14867075
Iteration 2, loss = 1.13179109
Iteration 3, loss = 0.60878241
Iteration 4, loss = 0.39485191
Iteration 5, loss = 0.22342504
Iteration 6, loss = 0.19081389
Iteration 7, loss = 0.19804336
Iteration 8, loss = 0.28273776
Iteration 9, loss = 0.26845659
Iteration 10, loss = 0.31277786
neural_network_with_settings: 2 - 0.940

/home/wikolego/miniconda3/envs/ml-3/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(

Iteration 1, loss = 4.45716556
Iteration 2, loss = 0.87086236
Iteration 3, loss = 0.41379547
Iteration 4, loss = 0.32124258
Iteration 5, loss = 0.16956773
Iteration 6, loss = 0.22373751
Iteration 7, loss = 0.28781245
Iteration 8, loss = 0.32056145
Iteration 9, loss = 0.23824041
Iteration 10, loss = 0.23665774
neural_network_with_settings: 3 - 0.918

/home/wikolego/miniconda3/envs/ml-3/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(

Iteration 1, loss = 4.55744443
Iteration 2, loss = 1.04101593
Iteration 3, loss = 0.47043711
Iteration 4, loss = 0.32410195
Iteration 5, loss = 0.38095589
Iteration 6, loss = 0.30165289
Iteration 7, loss = 0.20324692
Iteration 8, loss = 0.25861662
Iteration 9, loss = 0.21933119
Iteration 10, loss = 0.20686726
neural_network_with_settings: 4 - 0.936

/home/wikolego/miniconda3/envs/ml-3/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(

## Metryki

In [18]:
metrics_dict

{'SGDClassifier': [0.889, 0.8535, 0.869, 0.8665, 0.867],
 'decision_tree_gini': [0.814, 0.803, 0.803, 0.799, 0.804],
 'decision_tree_entropy': [0.812, 0.8305, 0.8015, 0.802, 0.8155],
 'decision_tree_log_loss': [0.8135, 0.824, 0.8045, 0.8105, 0.821],
 'random_forest': [0.95, 0.9545, 0.9535, 0.9485, 0.9565],
 'neural_network_default': [0.9295, 0.933, 0.9235, 0.919, 0.924],
 'neural_network_with_settings': [0.933, 0.9385, 0.94, 0.9185, 0.9365]}

## Metryki w DataFrame-ach

In [19]:
metrics_df = pd.DataFrame(metrics_dict)

display(metrics_df)
display(metrics_df.mean().to_frame().transpose().rename(index={0: "avg"}))

,SGDClassifier,decision_tree_gini,decision_tree_entropy,decision_tree_log_loss,random_forest,neural_network_default,neural_network_with_settings
0,0.8890,0.814,0.8120,0.8135,0.9500,0.9295,0.9330
1,0.8535,0.803,0.8305,0.8240,0.9545,0.9330,0.9385
2,0.8690,0.803,0.8015,0.8045,0.9535,0.9235,0.9400
3,0.8665,0.799,0.8020,0.8105,0.9485,0.9190,0.9185
4,0.8670,0.804,0.8155,0.8210,0.9565,0.9240,0.9365

,SGDClassifier,decision_tree_gini,decision_tree_entropy,decision_tree_log_loss,random_forest,neural_network_default,neural_network_with_settings
avg,0.869,0.8046,0.8123,0.8147,0.9526,0.9258,0.9333

In [20]:
metrics_df_tran = pd.DataFrame(metrics_dict).transpose()

display(metrics_df_tran)
display(metrics_df_tran.mean(axis=1).to_frame().rename(columns={0: "avg"}))

                                   0       1       2       3       4
SGDClassifier                 0.8890  0.8535  0.8690  0.8665  0.8670
decision_tree_gini            0.8140  0.8030  0.8030  0.7990  0.8040
decision_tree_entropy         0.8120  0.8305  0.8015  0.8020  0.8155
decision_tree_log_loss        0.8135  0.8240  0.8045  0.8105  0.8210
random_forest                 0.9500  0.9545  0.9535  0.9485  0.9565
neural_network_default        0.9295  0.9330  0.9235  0.9190  0.9240
neural_network_with_settings  0.9330  0.9385  0.9400  0.9185  0.9365

                                 avg
SGDClassifier                 0.8690
decision_tree_gini            0.8046
decision_tree_entropy         0.8123
decision_tree_log_loss        0.8147
random_forest                 0.9526
neural_network_default        0.9258
neural_network_with_settings  0.9333